{
 "title": "LACON-GO-TINY-SCRAPY",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of websites left to download",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "website_left_to_download_gauge", "legendFormat": "{{website}}" }
   ]
  },
  {
   "title": "Download latency per website",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "rate(crawler_worker_summary_sum[1m]) / rate(crawler_worker_summary_count[1m])",
     "legendFormat": "{{website}}"
    }
   ]
  },
  {
   "title": "Rate of successes per website",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(successful_download_count[1m])",
     "legendFormat": "{{website}}"
    }
   ]
  },
  {
   "title": "Download status codes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(downloads_status_counts[1m])",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  {
   "title": "Rate of errors while dowloading",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(download_error_count[1m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Crawling worker count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "crawler_worker_count", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Temp stopped crawler workers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "number_of_stopped_workers", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Rate of timeouts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(timeouts_count[1m])", "legendFormat": "{{website}}" }
   ]
  },
  {
   "title": "Parser worker count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "parser_worker_count", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Parser latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 7 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "rate(parser_worker_summary_sum[1m]) / rate(parser_worker_summary_count[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Database worker count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "database_worker_count", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Database latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 13 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "rate(database_worker_summary_sum[1m]) / rate(database_worker_summary_count[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=\"lacon-go-tiny-scrapy:8080\"}"
    }
   ]
  },
  {
   "title": "Number of GO routines",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=\"lacon-go-tiny-scrapy:8080\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 19 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])"
    }
   ]
  }
 ]
}