version: "3.1"

volumes:
    prometheus_data: {}
    grafana_data: {}
    mysql_db_data: {}

networks:
  lacon-net:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:v2.23.0
    container_name: lacon-go-tiny-scrapy-prometheus
    volumes:
    - ./resources/:/etc/prometheus/
    - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=1d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - lacon-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:7.3.5-ubuntu
    container_name: lacon-go-tiny-scrapy-grafana
    depends_on:
      - prometheus
    expose:
      - 9090
    ports:
      - 3000:3000
    user: "472"
    networks:
      - lacon-net
    environment:
      - GF_SECURITY_ADMIN_USER=engri_user
      - GF_SECURITY_ADMIN_PASSWORD=engri_password
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./resources/grafana:/etc/grafana/provisioning
    restart: unless-stopped

  lacon-go-tiny-scrapy:
    container_name: lacon-go-tiny-scrapy-service
    depends_on:
      - prometheus
      - graylog
      - mysql-db
    networks:
      - lacon-net
    build: .
    restart: unless-stopped
    environment:
      DB_NAME: engri
      DB_USERNAME: engri_user
      DB_PASSWORD: engri_password
      DB_HOST: mysql-db

  # MongoDB: https://hub.docker.com/_/mongo/
  mongo:
    container_name: lacon-go-tiny-scrapy-mongo-db
    image: mongo:4.2
    networks:
      - lacon-net
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docker.html
  elasticsearch:
    container_name: lacon-go-tiny-scrapy-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - lacon-net
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    container_name: lacon-go-tiny-scrapy-graylog
    image: graylog/graylog:4.0
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    networks:
      - lacon-net
    restart: always
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    expose:
      - 9000

  mysql-db:
    container_name: lacon-go-tiny-scrapy-mysql-db
    image: mysql:5.7
    networks:
      - lacon-net
    volumes:
      - mysql_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: engri
      MYSQL_USER: engri_user
      MYSQL_PASSWORD: engri_password
    ports:
      - 2200:3306
